# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

# Site settings
title: Jing0 's blog
author: Jackie Kuo
email: j.kuo2012@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is Jing0's blog.I share coding,reading,music and some thoughts about life here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jackiekuo.com" # the base hostname & protocol for your site
github_username:  jing0

comments : true
#  provider : disqus
#  disqus :
#    short_name : jing0sblog

# Build settings
markdown: kramdown
